DEFINITIONS:
  task_configs:
    - &busybox-config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
        - name: myfork


resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

resources:
  - name: keyval
    type: keyval

  - name: myfork
    type: git
    source:
      uri: https://github.com/jeffwatts/concourse-tutorial
      branch: jeff/noodling

jobs:
  - name: build
    plan:
      - get: myfork
      - task: something-random
        config:
          <<: *busybox-config
          run: {path: myfork/jeffpipeline/random-script.sh}
        on_success:
          task: success-task-props
          config:
            <<: *busybox-config
            outputs:
              - name: keyvalout
            run: {path: myfork/jeffpipeline/success-script-props.sh}
        on_failure:
          task: fail-task-props
          config:
            <<: *busybox-config
            outputs:
              - name: keyvalout
            run: {path: myfork/jeffpipeline/fail-script-props.sh}
        ensure:
          put: keyval
          params:
            file: keyvalout/keyval.properties

  - name: post-build
    plan:
      - get: myfork
      - get: keyval
        passed:
          - build
      - task: val-check
        config:
          <<: *busybox-config
          inputs:
            - name: myfork
            - name: keyval
          run:
            path: myfork/jeffpipeline/read-props.sh

