DEFINITIONS:
  task_configs:
    - &busybox-config
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: busybox
      inputs:
        - name: myfork


resource_types:
  - name: keyval
    type: docker-image
    source:
      repository: swce/keyval-resource

resources:
  - name: keyval
    type: keyval

  - name: myfork
    type: git
    source:
      uri: https://github.com/jeffwatts/concourse-tutorial
      branch: jeff/noodling

jobs:
  - name: build
    plan:
      - get: myfork
      - aggregate:
        - task: do-something
          config:
            <<: *busybox-config
            run:
              path: ./myfork/random-script.sh
        - task: set-up-props
          config:
            <<: *busybox-config
            outputs:
              - name: keyvalout
            run:
              path: myfork/jeffpipeline/set-up-props.sh
        on_success:
          task: success-task
          config:
            <<: *busybox-config
            run: {path: myfork/success-script.sh}
        on_failure:
          task: fail-task
          config:
            <<: *busybox-config
            run: {path: myfork/fail-script.sh}
      - put: keyval
        params:
          file: keyvalout/keyval.properties

  - name: post-build
    plan:
      - get: myfork
      - get: keyval
        passed:
          - build
      - task: val-check
        config:
          <<: *busybox-config
          inputs:
            - name: myfork
            - name: keyval
          run:
            path: myfork/jeffpipeline/read-props.sh

